project:
  type: website
  output-dir: docs

website:
  title: "TRGN-515"
  description: "Advanced Human Genomic Analysis Methods"
  
  # The top navigation bar
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: modules.qmd
        text: Modules
    right:
      - icon: github
        href: https://github.com/trgn-515
        aria-label: GitHub

  # The side navigation menu
  sidebar:
    style: "docked"
    search: true
    contents:
      - section: "Module 0: Sequencing technologies"
        contents:
          - modules/0_intro_git/0_intro_git.qmd
      - section: "Module 1: Sequencing technologies"
        contents:
          - modules/1_sequencing_techs/1_sequencing_techs.qmd
      - section: "Module 2: Structural Variants"
        contents:
          - modules/2_sv/2_sv.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    toc-depth: 4

